config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/home'

  get 'static_pages/home'
  get 'static_pages/help'

  get 'sessions/new'

  resources :principles
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'application#goodbye'
  get    '/help',    to: 'static_pages#help'
  get    '/about',   to: 'static_pages#about'
  get    '/contact', to: 'static_pages#contact'
  get    '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/principle.rb
class Principle < ApplicationRecord
  belongs_to :user
  validates :content, length: { maximum: 40 }
  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :principles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  def hello
    render html: "hello,world"
  end

  def goodbye
    render html: "goodbye, world"
  end
end

app/controllers/principles_controller.rb
class PrinciplesController < ApplicationController
  before_action :set_principle, only: [:show, :edit, :update, :destroy]

  # GET /principles
  # GET /principles.json
  def index
    @principles = Principle.all
  end

  # GET /principles/1
  # GET /principles/1.json
  def show
  end

  # GET /principles/new
  def new
    @principle = Principle.new
  end

  # GET /principles/1/edit
  def edit
  end

  # POST /principles
  # POST /principles.json
  def create
    @principle = Principle.new(principle_params)

    respond_to do |format|
      if @principle.save
        format.html { redirect_to @principle, notice: 'Principle was successfully created.' }
        format.json { render :show, status: :created, location: @principle }
      else
        format.html { render :new }
        format.json { render json: @principle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /principles/1
  # PATCH/PUT /principles/1.json
  def update
    respond_to do |format|
      if @principle.update(principle_params)
        format.html { redirect_to @principle, notice: 'Principle was successfully updated.' }
        format.json { render :show, status: :ok, location: @principle }
      else
        format.html { render :edit }
        format.json { render json: @principle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /principles/1
  # DELETE /principles/1.json
  def destroy
    @principle.destroy
    respond_to do |format|
      format.html { redirect_to principles_url, notice: 'Principle was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_principle
      @principle = Principle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def principle_params
      params.require(:principle).permit(:name, :team_id, :content, :index, :principle_explain)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/principles_helper.rb
module PrinciplesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
%html
  %head
    %title
      = csrf_meta_tags
      = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
      = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/principles/_form.html.haml
= form_for(principle) do |f|
  - if principle.errors.any?
    #error_explanation
      %h2
        = pluralize(principle.errors.count, "error")
        prohibited this principle from being saved:
      %ul
        - principle.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :team_id
    = f.number_field :team_id
  .field
    = f.label :content
    = f.text_area :content
  .field
    = f.label :index
    = f.number_field :index
  .field
    = f.label :principle_explain
    = f.text_area :principle_explain
  .actions
    = f.submit

app/views/principles/edit.html.haml
%h1 Editing Principle
= render 'form', principle: @principle
= link_to 'Show', @principle
|
= link_to 'Back', principles_path

app/views/principles/index.html.haml
%p#notice= notice
%h1 Principles
%table
  %thead
    %tr
      %th Name
      %th Team
      %th Content
      %th Index
      %th Principle explain
      %th{:colspan => "3"}
  %tbody
    - @principles.each do |principle|
      %tr
        %td= principle.name
        %td= principle.team_id
        %td= principle.content
        %td= principle.index
        %td= principle.principle_explain
        %td= link_to 'Show', principle
        %td= link_to 'Edit', edit_principle_path(principle)
        %td= link_to 'Destroy', principle, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Principle', new_principle_path

app/views/principles/new.html.haml
%h1 New Principle
= render 'form', principle: @principle
= link_to 'Back', principles_path

app/views/principles/show.html.haml
%p#notice= notice
%p
  %strong Name:
  = @principle.name
%p
  %strong Team:
  = @principle.team_id
%p
  %strong Content:
  = @principle.content
%p
  %strong Index:
  = @principle.index
%p
  %strong Principle explain:
  = @principle.principle_explain
= link_to 'Edit', edit_principle_path(@principle)
|
= link_to 'Back', principles_path

app/views/static_pages/help.html.haml
!!!
%html
  %head
    %title
      Help | Ruby on Rails Tutorial Sample App
  %body
    %h1
      Help
    %p
      Get help on the Ruby on Rails Tutorial at the
    %a{href: "http://railstutorial.jp/help"}
      Rails Tutorial help page. To get help on this sample app, see the
    %a{href: "http://railstutorial.jp/book"}
      %em
        Ruby on Rails Tutorial book.

app/views/static_pages/home.html.haml
<% provide(:title, "Home") %>
%h1
  Sample App
%p
  This is the home page for the
  %a{href: "http://railstutorial.jp/"}
    Ruby on Rails Tutorial.sample application.

app/views/users/_form.html.haml
= form_for(user) do |f|
  - if user.errors.any?
    #error_explanation
      %h2
        = pluralize(user.errors.count, "error")
        prohibited this user from being saved:
      %ul
        - user.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :username
    = f.text_field :username
  .field
    = f.label :email
    = f.text_field :email
  .field
    = f.label :password
    = f.text_field :password
  .actions
    = f.submit

app/views/users/edit.html.haml
%h1 Editing User
  = render 'form', user: @user
  = link_to 'Show', @user
  = link_to 'Back', users_path

app/views/users/index.html.haml
%p{id: "notice"}
  = notice

%h1
  Users

%table
  %thead
    %tr
      %th
        Username
      %th
        Email
      %th
        Password
      %th{colspan: "3"}

  %tbody
    - @users.each do |user|
      %tr
        %td
          = user.username
        %td
          = user.email
        %td
          = user.password
        %td
          = link_to 'Show', user
        %td
          = link_to 'Edit', edit_user_path(user)
        %td
          = link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }

%br
= link_to 'New User', new_user_path 

app/views/users/new.html.haml
%h1 New User
= render 'form', user: @user
= link_to 'Back', users_path

app/views/users/show.html.haml
%p#notice= notice
%p
  %strong Username:
  = @user.username
%p
  %strong Email:
  = @user.email
%p
  %strong Password:
  = @user.password
= link_to 'Edit', edit_user_path(@user)
|
= link_to 'Back', users_path